[package]
name = "lipl-sample-data"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lipl-core = { path = "../lipl-core" }
parts = { path = "../parts" }

[build-dependencies]
quote = "1.0.21"
rust-format = { version = "0.3.4", features = ["token_stream"] }
