[package]
authors.workspace = true
description = "Redis storage"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-redis"
repository.workspace = true
version.workspace = true

[dependencies]
lipl-core = { version = "0.5", path = "../lipl-core" }
bb8-redis = "0.24.0"
futures-util = "0.3.31"
tokio = "1.46.1"

[dev-dependencies]
tokio = { version = "1.46.1", features = ["rt", "macros"] }
tracing-subscriber = "0.3.19"
