[package]
name = "parts"
version = "0.1.0"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[dependencies]
regex = "1.4"
futures = "0.3"
lazy_static = "1"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
