[package]
authors.workspace = true
description = "Postgres storage backend for Axum"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-postgres"
repository.workspace = true
version.workspace = true

[dependencies]
bb8-postgres = "0.9.0"
futures-util = "0.3.31"
lipl-core = { version = "0.5", path = "../lipl-core" }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = "1"
tokio-postgres = { version = "0.7.13", features = ["with-uuid-1"] }
tracing = "0.1.41"
